Modulo 2/Actividad 2.2/Test/Apps/home/urls.py
from django.contrib import admin
from django.urls import path
from .views import homeView,creditosView

app_name='app1'

urlpatterns = [
    path('index/', homeView.as_view(), name='home'),
    path('creditos/', creditosView.as_view(), name='creditos'),
]

Modulo 2/Actividad 2.2/Test/Test/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('Apps.home.urls')),
]

Modulo 2/Actividad 2.2/Test/Apps/home/models.py
from django.db import models

# Create your models here.

Modulo 2/Actividad 2.2/Test/Apps/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class homeView(TemplateView):
    template_name='index.html'

class creditosView(TemplateView):
    template_name='creditos.html'

Modulo 2/Actividad 2.2/Test/Apps/home/templates/acerca_de.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Acerca De</title>
</head>
<body>
    
</body>
</html>

Modulo 2/Actividad 2.2/Test/Apps/home/templates/administradores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Administrador</title>
</head>
<body>
    
</body>
</html>

Modulo 2/Actividad 2.2/Test/Apps/home/templates/creditos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Creditos</title>
</head>
<body>
    <h2>BIENVENIDOS</h2>
    <h3>CREDITOS LAS 24 HORAS</h3>
    <h3>PROPIETARIO: ESTUDIANTES UMG</h3>
    <a href="{% url 'app1:home' %}">home</a>
</body>
</html>

Modulo 2/Actividad 2.2/Test/Apps/home/templates/estudiantes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estudiantes</title>
</head>
<body>
    
</body>
</html>

Modulo 2/Actividad 2.2/Test/Apps/home/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>

</body>
</html>

Modulo 2/Actividad 2.2/Test/Apps/home/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Principal</title>
</head>
<body>
    <h1>PÁGINA PRINCIPAL</h1>
    <h2>....................................................</h2>
    <a href="{% url 'app1:creditos' %}">creditos</a>
</body>
</html>